[package]
org = "induwarag"
name = "find_approximate_duplicates"
version = "0.1.0"
distribution = "2201.11.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "induwaragm"
name = "etl"
version = "0.1.0"
repository="local"